import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "GohuFont uni11 Nerd Font", style = "Medium" }
bold = { family = "GohuFont uni11 Nerd Font", style = "Bold" }
italic = { family = "GohuFont uni11 Nerd Font", style = "Medium Italic" }
bold_italic = { family = "GohuFont uni11 Nerd Font", style = "Bold Italic" }
size=8

[window]
startup_mode = "Windowed"
title = "Terminal"
decorations_theme_variant = "None"
decorations = "Full"
opacity = 0.75

[shell]
program = "/usr/bin/tmux"
