[mgr]
prepend_keymap = [
  # Bunny.yazi, meu plugin favorito at√© agora.
{ desc = "Start bunny.yazi fuzzy search", on = "'", run = "plugin bunny fuzzy" },
{ desc = "Start bunny.yazi", on = ";", run = "plugin bunny" },

  # Recycle-bin, a lixeira ebaaaa!!!
  { on = ["R","o"], run = "plugin recycle-bin -- open",        desc = "Open Trash" },
  { on = ["R","e"], run = "plugin recycle-bin -- empty",       desc = "Empty Trash" },
  { on = ["R","D"], run = "plugin recycle-bin -- emptyDays",   desc = "Empty by days deleted" },
  { on = ["R","d"], run = "plugin recycle-bin -- delete",      desc = "Delete from Trash" },
  { on = ["R","r"], run = "plugin recycle-bin -- restore",     desc = "Restore from Trash" },
]
