[mgr]
# Se você usa o layout padrão de duas colunas (Arquivos + Preview):
# [Painel de Arquivos, Painel de Visualização]
ratio = [0, 2, 4]

[[plugin.prepend_previewers]]
url = "*/"
run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"'

[[plugin.prepend_previewers]]
url = "*.{jpg,jpeg,png,gif,webp,ico}"
run = 'piper -- CLICOLOR_FORCE=1 chafa --size="$w"x"$h" "$1"'

[[plugin.prepend_previewers]]
url = "*.tar*"
run = 'piper --format=url -- tar tf "$1"'

[[plugin.prepend_previewers]]
url = "*"
run = 'piper -- batcat -p --color=always --theme="Catppuccin Mocha" "$1"'

